# Generated by Django 3.0 on 2019-12-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
