# Generated by Django 3.0 on 2019-12-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_license_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='api.License'),
        ),
    ]
