# Generated by Django 3.0 on 2019-12-10 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to='api.Item')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
