# Generated by Django 3.0 on 2019-12-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
